[build]
  command = "npm run generate"
  publish = ".output/public"
  
[build.environment]
  NODE_VERSION = "18"

# Configuration des redirects pour gérer les routes SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Variables d'environnement pour la production
[context.production.environment]
  API_URL = "https://birth-app-6syx.onrender.com"  # URL mise à jour de l'API sur Render
